# backend/src/api/routes/recommendations.py
"""
Recommendations Routes — Warif API
=====================================
Handles AI-generated recommendation endpoints:
  - GET  /{farm_id}                              : list recommendations with filters
  - POST /{farm_id}/mark-read/{id}               : mark a recommendation as read
  - POST /{farm_id}/mark-all-read                : mark all recommendations as read
  - POST /{farm_id}/feedback/{id}                : submit helpful/not helpful feedback
  - GET  /{farm_id}/feedback-stats               : get feedback accuracy statistics

Recommendations are generated by the Decision Engine on every sensor reading.
All endpoints require JWT authentication and farm ownership verification.
"""
import asyncio
import json
import re
from typing import List, Optional
from datetime import datetime, timezone, timedelta
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc, Integer, func
from pydantic import BaseModel

from src.db.session import get_db
from src.db.models.models import (
    Recommendation, Farm, ActivityLog, SensorReading, DeviceCommand,
    Device, Actuator, IrrigationCommand, IrrigationEvent, IrrigationMode,
    IrrigationStatus,
)
from src.api.schemas.schemas import RecommendationOut
from src.core.security import get_current_user
from src.services import tuya_client
from src.services.decision_engine import get_engine
from src.services.recommendation_suppression import get_current_decision_state
# PresentationFormatter removed — formatting is handled inline per endpoint


class FeedbackRequest(BaseModel):
    # Request body for recommendation feedback — farmer rates if recommendation was useful
    helpful: bool


class RecommendationActionRequest(BaseModel):
    status: str


class ExecuteRecommendationRequest(BaseModel):
    mode: str = "manual"
    duration_min: int = 15


router = APIRouter()
AUTO_RECOMMENDATION_STATUS_ROLLOUT = datetime(2026, 6, 2, 0, 0, tzinfo=timezone.utc)


# Returns filtered recommendations for a farm — supports category, severity, type, and unread filters
@router.get("/{farm_id}", response_model=List[dict])
async def list_recommendations(
    farm_id: int,
    category: Optional[str] = Query(None, description="irrigation | temperature | humidity | soil | general"),
    severity: Optional[str] = Query(None, description="normal | warning | urgent"),
    type: Optional[str] = Query(None, description="urgent | improvement"),
    since: Optional[datetime] = Query(None, description="Return recommendations created at or after this UTC timestamp"),
    unread_only: bool = Query(False),
    limit: int = Query(50, le=5000),
    include_state: bool = Query(True, description="Include live decision state for recommendation cards"),
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """List recommendations for a farm, filterable by category, severity, and type."""
    farm = await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    q = (
        select(Recommendation)
        .where(Recommendation.farm_id == farm_id)
        .order_by(desc(Recommendation.created_at))
        .limit(limit)
    )
    if category:
        q = q.where(Recommendation.category == category)
    if severity:
        q = q.where(Recommendation.severity == severity)
    if since:
        since_utc = since if since.tzinfo else since.replace(tzinfo=timezone.utc)
        q = q.where(Recommendation.created_at >= since_utc)
    if type == "urgent":
        q = q.where((Recommendation.is_alert == True) | (Recommendation.severity.in_(["urgent", "warning"])))  # noqa: E712
    elif type == "improvement":
        q = q.where((Recommendation.is_alert == False) & (Recommendation.severity == "normal"))  # noqa: E712
    if unread_only:
        q = q.where(Recommendation.is_read == False)  # noqa: E712

    result = await db.execute(q)
    recommendations = result.scalars().all()

    def normalize_category(value: Optional[str]) -> str:
        raw = (value or "general").lower()
        if raw in ("air_temperature", "temperature", "climate"):
            return "temperature"
        if raw in ("air_humidity", "humidity"):
            return "humidity"
        if raw in ("soil_temperature", "soil"):
            return "soil"
        if raw in ("soil_moisture", "irrigation", "water"):
            return "irrigation"
        return raw

    # Serialize recommendations — safely extract enum values for frontend
    def infer_source_sensor_type(category_value: str, message: Optional[str], reasoning: Optional[str]) -> Optional[str]:
        text = f"{message or ''} {reasoning or ''}".lower()
        if category_value == "temperature":
            return "air_temperature"
        if category_value == "humidity":
            return "air_humidity"
        if category_value == "soil":
            return "soil_temperature"
        if category_value == "irrigation":
            if "soil" in text or "تربة" in text or "رطوبة التربة" in text:
                return "soil_moisture"
            return "water_usage"
        return None

    latest_sensor_data = await _latest_sensor_snapshot(farm_id, db)
    professional_recs = []
    status_changed = False
    for rec in recommendations:
        try:
            # Safely extract enum string values for category and severity
            category_value = rec.category.value if hasattr(rec.category, 'value') else str(rec.category)
            severity_value = rec.severity.value if hasattr(rec.severity, 'value') else str(rec.severity)
            normalized_category = normalize_category(category_value)
            action_status = rec.mode if rec.mode in ("executed", "ignored", "deferred", "auto", "legacy", "stale", "executing") else None
            action_status = await _resolve_live_recommendation_status(db, farm_id, rec, normalized_category, action_status)
            if action_status == "executed" and rec.mode != "executed":
                rec.mode = "executed"
                status_changed = True
            if (
                not action_status
                and getattr(farm, "auto_mode", False)
                and _is_before_auto_status_rollout(rec.created_at)
            ):
                action_status = "legacy"
            decision_state = None
            reading_mismatch_reason = _recommendation_reading_mismatch_reason(rec, latest_sensor_data, normalized_category)
            if reading_mismatch_reason and action_status not in {"executed", "ignored"}:
                action_status = "stale"
                decision_state = _stale_recommendation_state(reading_mismatch_reason)
            if include_state:
                decision_state = decision_state or await get_current_decision_state(
                    db=db,
                    farm_id=farm_id,
                    category=normalized_category,
                    message=rec.message,
                    created_at=rec.created_at,
                )
            if action_status == "executed" and decision_state and decision_state.get("state") == "hold":
                decision_state = {
                    **decision_state,
                    "state": "completed",
                    "label": "تم التنفيذ",
                    "label_en": "Completed",
                    "reason": "تم تنفيذ التوصية ولا يوجد إجراء نشط حاليا.",
                    "reason_en": "The recommendation was executed and no action is active now.",
                }
            if action_status in {"deferred", "legacy", "auto", "executing"} and not decision_state:
                decision_state = _decision_state_from_action_status(action_status, normalized_category, rec.message, rec.reasoning)

            professional_recs.append({
                "id": rec.id,
                "source": "recommendation",
                "title": rec.message[:60] if rec.message else "توصية",
                "message": rec.message,
                "reasoning": rec.reasoning,
                "category": normalized_category,
                "source_sensor_type": infer_source_sensor_type(normalized_category, rec.message, rec.reasoning),
                "severity": severity_value,
                "is_read": rec.is_read,
                "is_alert": rec.is_alert,
                "helpful": rec.helpful,
                "feedback_at": rec.feedback_at.isoformat() if rec.feedback_at else None,
                "action_status": action_status,
                "decision_state": decision_state,
                "created_at": rec.created_at.isoformat() if rec.created_at else None,
            })
        except Exception as e:
            print(f"[ERROR] Recommendation {rec.id}: {e}")
            continue

    professional_recs.sort(key=lambda item: item.get("created_at") or "", reverse=True)
    professional_recs = professional_recs[:limit]
    if status_changed:
        await db.commit()

    return professional_recs


def _is_before_auto_status_rollout(value: Optional[datetime]) -> bool:
    if value is None:
        return False
    utc_value = value.replace(tzinfo=timezone.utc) if value.tzinfo is None else value.astimezone(timezone.utc)
    return utc_value < AUTO_RECOMMENDATION_STATUS_ROLLOUT


async def _resolve_live_recommendation_status(
    db: AsyncSession,
    farm_id: int,
    rec: Recommendation,
    category: str,
    action_status: Optional[str],
) -> Optional[str]:
    if action_status != "executing":
        return action_status

    decision = rec.execution_action or {}
    action = decision.get("action")
    if not action:
        return "auto"

    if category == "irrigation":
        active = await _is_irrigation_running(db, farm_id)
        if action == "start":
            return "executing" if active else "executed"
        if action == "stop":
            return "executed" if not active else "executing"

    if category in {"temperature", "humidity", "climate"}:
        current_mode = await _latest_climate_mode(db, farm_id)
        expected_mode = "full" if action == "cooling_full" else "fan_only" if action == "fan_only" else "stop" if action == "stop" else None
        if expected_mode:
            if expected_mode == "stop":
                return "executed" if current_mode == "stop" else "executing"
            return "executing" if current_mode == expected_mode else "executed"

    return "auto"


async def _is_irrigation_running(db: AsyncSession, farm_id: int) -> bool:
    result = await db.execute(
        select(IrrigationEvent)
        .join(IrrigationCommand)
        .join(Actuator)
        .join(Device)
        .where(
            Device.farm_id == farm_id,
            IrrigationEvent.status == IrrigationStatus.active,
        )
        .order_by(desc(IrrigationEvent.timestamp))
        .limit(1)
    )
    return result.scalar_one_or_none() is not None


async def _latest_climate_mode(db: AsyncSession, farm_id: int) -> str:
    result = await db.execute(
        select(ActivityLog)
        .where(
            ActivityLog.farm_id == farm_id,
            ActivityLog.action_type.in_([
                "manual_cooling_full",
                "manual_cooling_fan_only",
                "manual_cooling_stop",
                "auto_cooling_full",
                "auto_cooling_fan_only",
                "auto_cooling_stop",
            ]),
        )
        .order_by(desc(ActivityLog.created_at), desc(ActivityLog.id))
        .limit(1)
    )
    latest = result.scalar_one_or_none()
    if not latest:
        return "stop"
    details = latest.details or {}
    return details.get("mode") or ("full" if "full" in latest.action_type else "fan_only" if "fan_only" in latest.action_type else "stop")


def _decision_state_from_action_status(action_status: str, category: str, message: Optional[str], reasoning: Optional[str]) -> Optional[dict]:
    if action_status == "legacy":
        return {
            "state": "monitoring",
            "domain": category,
            "label": "لا يتطلب إجراء الآن",
            "label_en": "No Action Needed Now",
            "reason": "القراءات الحالية لا تحتاج أمر جهاز الآن. سيعيد النظام تقييم هذه التوصية عند وصول قراءة حساسات جديدة.",
            "reason_en": "The latest readings do not require a device command right now. The system will re-evaluate this recommendation when new sensor data arrives.",
        }

    if action_status == "auto":
        if category == "irrigation":
            return {
                "state": "blocked",
                "domain": category,
                "label": "ري مؤجل",
                "label_en": "Irrigation Deferred",
                "reason": _deferred_reason(category, message, reasoning, "ar"),
                "reason_en": _deferred_reason(category, message, reasoning, "en"),
            }
        return {
            "state": "monitoring",
            "domain": category,
            "label": "لا يتطلب إجراء الآن",
            "label_en": "No Action Needed Now",
            "reason": _auto_action_message(category, message, reasoning, "ar"),
            "reason_en": _auto_action_message(category, message, reasoning, "en"),
        }

    if action_status == "executing":
        return {
            "state": "executing",
            "domain": category,
            "label": "قيد التنفيذ",
            "label_en": "In Progress",
            "reason": _auto_action_message(category, message, reasoning, "ar"),
            "reason_en": _auto_action_message(category, message, reasoning, "en"),
        }

    if action_status == "deferred":
        label = "ري مؤجل" if category == "irrigation" else "مؤجل"
        label_en = "Irrigation Deferred" if category == "irrigation" else "Deferred"
        return {
            "state": "blocked",
            "domain": category,
            "label": label,
            "label_en": label_en,
            "reason": _deferred_reason(category, message, reasoning, "ar"),
            "reason_en": _deferred_reason(category, message, reasoning, "en"),
        }

    return None


def _stale_recommendation_state(reason: str) -> dict:
    return {
        "state": "stale",
        "domain": "recommendation",
        "label": "لا يتطلب إجراء الآن",
        "label_en": "No Action Needed Now",
        "reason": reason,
        "reason_en": "The sensor reading changed after this recommendation was created. No device command is needed from this old recommendation; the system will rely on the latest recommendation when new readings arrive.",
    }


def _auto_action_message(category: str, message: Optional[str], reasoning: Optional[str], lang: str) -> str:
    text = f"{message or ''} {reasoning or ''}".lower()
    if category == "irrigation":
        if "إيقاف" in text or "ايقاف" in text or "stop" in text:
            return "The system is stopping irrigation to prevent soil saturation and protect roots." if lang == "en" else "يقوم النظام بإيقاف الري لتجنب تشبع التربة وحماية الجذور."
        return "The system is applying the irrigation decision and monitoring soil moisture response." if lang == "en" else "يقوم النظام بتطبيق قرار الري ومراقبة استجابة رطوبة التربة."
    if category == "humidity":
        return "Ventilation is running to reduce excess humidity and lower fungal-risk conditions." if lang == "en" else "نظام التهوية يعمل لتصريف الرطوبة الزائدة وتقليل ظروف خطر الأمراض الفطرية."
    if category == "temperature":
        return "Cooling and ventilation are running until temperature and humidity return to a stable range." if lang == "en" else "التبريد والتهوية يعملان حتى تعود الحرارة والرطوبة إلى نطاق مستقر."
    return "The system is applying this automatic decision and monitoring the related readings." if lang == "en" else "يقوم النظام بتطبيق هذا القرار التلقائي ومراقبة القراءات المرتبطة."


def _deferred_reason(category: str, message: Optional[str], reasoning: Optional[str], lang: str) -> str:
    text = f"{message or ''} {reasoning or ''}".lower()
    if category == "irrigation":
        if "ليل" in text or "night" in text or "فطر" in text or "fungal" in text:
            return (
                "The system did not start irrigation because the current period is nighttime. Watering now can keep leaves or soil wet for longer and increase fungal disease risk, so irrigation will be re-evaluated when safety conditions improve."
                if lang == "en"
                else "لم يشغّل النظام الري لأن الوقت الحالي فترة ليلية. الري الآن قد يبقي الأوراق أو التربة رطبة لفترة أطول ويزيد خطر الأمراض الفطرية، لذلك سيُعاد تقييم الري عند تحسن شروط السلامة."
            )
        if "تشبع" in text or "تعفن" in text or "saturat" in text or "root" in text:
            return "Irrigation is deferred because soil moisture is high or near saturation, and watering now may increase root-rot risk." if lang == "en" else "تم تأجيل الري لأن رطوبة التربة مرتفعة أو قريبة من التشبع، وتشغيل المضخة الآن قد يزيد خطر تعفن الجذور."
        return "Irrigation is deferred by the current safety checks. The system will re-evaluate the pump decision when soil moisture and environmental conditions allow it." if lang == "en" else "تم تأجيل الري بسبب فحوصات السلامة الحالية. سيعيد النظام تقييم قرار المضخة عندما تسمح رطوبة التربة والظروف البيئية بذلك."
    if category == "temperature":
        return "Cooling was not started because the latest automatic decision did not require a new cooling command or the climate system is already in the requested state." if lang == "en" else "لم يبدأ التبريد لأن القرار التلقائي الأخير لم يحتج أمر تبريد جديد أو لأن نظام المناخ في الحالة المطلوبة بالفعل."
    if category == "humidity":
        return "Ventilation was not started because the latest automatic decision did not require a new fan command or the fans are already in the requested state." if lang == "en" else "لم تبدأ التهوية لأن القرار التلقائي الأخير لم يحتج أمر مروحة جديد أو لأن المراوح في الحالة المطلوبة بالفعل."
    return "This recommendation is deferred because there is no direct actuator command available for it in the current automatic control cycle." if lang == "en" else "تم تأجيل هذه التوصية لعدم وجود أمر جهاز مباشر لها في دورة التحكم التلقائي الحالية."


@router.post("/{farm_id}/action/{recommendation_id}", response_model=dict)
async def record_recommendation_action(
    farm_id: int,
    recommendation_id: int,
    action: RecommendationActionRequest,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """Persist the user's execute/ignore decision for a recommendation."""
    await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    result = await db.execute(
        select(Recommendation).where(
            Recommendation.id == recommendation_id,
            Recommendation.farm_id == farm_id,
        )
    )
    rec = result.scalar_one_or_none()
    if not rec:
        raise HTTPException(status_code=404, detail="Recommendation not found")

    status = action.status.strip().lower()
    if status not in ("executed", "ignored"):
        raise HTTPException(status_code=422, detail="status must be executed or ignored")

    if status == "executed":
        log = ActivityLog(
            farm_id=farm_id,
            user_id=int(current_user["sub"]),
            action_type="recommendation_executed",
            details={
                "recommendation_id": recommendation_id,
                "category": rec.category.value if hasattr(rec.category, "value") else str(rec.category),
                "message": rec.message,
            },
            performed_by="user",
        )
        db.add(log)
    rec.is_read = True
    rec.mode = status
    await db.commit()

    return {
        "success": True,
        "recommendation_id": recommendation_id,
        "action_status": status,
    }


@router.post("/{farm_id}/execute/{recommendation_id}", response_model=dict)
async def execute_recommendation(
    farm_id: int,
    recommendation_id: int,
    body: ExecuteRecommendationRequest = ExecuteRecommendationRequest(),
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """Execute a recommendation through the current Decision Engine action contract."""
    farm = await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    result = await db.execute(
        select(Recommendation).where(
            Recommendation.id == recommendation_id,
            Recommendation.farm_id == farm_id,
        )
    )
    rec = result.scalar_one_or_none()
    if not rec:
        raise HTTPException(status_code=404, detail="Recommendation not found")

    sensor_data = await _latest_sensor_snapshot(farm_id, db)
    sensor_data["crop_type"] = farm.crop_type or "tomatoes"

    engine = get_engine()
    report = await engine.analyze_with_intelligence(sensor_data, farm_id)
    category = _normalize_category(rec.category.value if hasattr(rec.category, "value") else str(rec.category))
    execution = _recommendation_saved_execution_action(rec, category) or _recommendation_execution_intent(rec, category)
    executable_category = execution["category"] if execution else category
    if executable_category not in {"irrigation", "temperature", "humidity"}:
        raise HTTPException(status_code=422, detail=f"Recommendation category '{category}' is not directly executable")

    domain = "irrigation" if executable_category == "irrigation" else "climate"
    decision = report.get("action_decisions", {}).get(domain)
    mode = (body.mode or "manual").lower()
    is_auto = mode == "auto"
    mismatch_reason = _recommendation_reading_mismatch_reason(rec, sensor_data, executable_category)
    if mismatch_reason and not is_auto:
        raise HTTPException(status_code=409, detail=mismatch_reason)

    if (not decision or decision.get("action") == "hold") and execution and not mismatch_reason:
        decision = execution["decision"]
    if not decision:
        raise HTTPException(status_code=422, detail="No executable decision is available for this recommendation")
    if decision.get("action") == "hold":
        if not is_auto:
            return {
                "success": True,
                "executed": False,
                "recommendation_id": recommendation_id,
                "domain": domain,
                "decision": decision,
                "result": {
                    "action": "hold",
                    "reason": (
                        "لم يتم تنفيذ التوصية لأن القراءة الحالية أو شروط السلامة لا تتطلب هذا الإجراء الآن. "
                        "راجع أحدث توصية قبل تشغيل الجهاز."
                    ),
                },
            }
        return {
            "success": True,
            "executed": False,
            "recommendation_id": recommendation_id,
            "domain": domain,
            "decision": decision,
            "result": {"action": "hold", "reason": decision.get("reason")},
        }

    if domain == "irrigation":
        result_payload = await _execute_irrigation_decision(
            db=db,
            farm_id=farm_id,
            recommendation_id=recommendation_id,
            decision=decision,
            duration_min=body.duration_min,
            is_auto=is_auto,
        )
    else:
        result_payload = await _execute_climate_decision(
            db=db,
            farm_id=farm_id,
            recommendation_id=recommendation_id,
            decision=decision,
            is_auto=is_auto,
        )

    rec.is_read = True
    rec.mode = "executing"
    db.add(ActivityLog(
        farm_id=farm_id,
        user_id=int(current_user["sub"]),
        action_type="recommendation_executed",
        details={
            "recommendation_id": recommendation_id,
            "category": category,
            "domain": domain,
            "decision": decision,
            "result": result_payload,
        },
        performed_by="system" if is_auto else "user",
    ))
    await db.commit()

    return {
        "success": True,
        "executed": True,
        "recommendation_id": recommendation_id,
        "domain": domain,
        "decision": decision,
        "result": result_payload,
    }


@router.post("/{farm_id}/mark-read/{recommendation_id}", response_model=RecommendationOut)
async def mark_as_read(
    farm_id: int,
    recommendation_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """Mark a recommendation as read."""
    await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    result = await db.execute(
        select(Recommendation).where(
            Recommendation.id == recommendation_id,
            Recommendation.farm_id == farm_id,
        )
    )
    rec = result.scalar_one_or_none()
    if not rec:
        raise HTTPException(status_code=404, detail="Recommendation not found")

    rec.is_read = True
    await db.commit()
    await db.refresh(rec)
    return rec


@router.post("/{farm_id}/mark-all-read", response_model=dict)
async def mark_all_read(
    farm_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """Mark all recommendations for a farm as read."""
    await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    result = await db.execute(
        select(Recommendation).where(
            Recommendation.farm_id == farm_id,
            Recommendation.is_read == False,  # noqa: E712
        )
    )
    recs = result.scalars().all()
    for rec in recs:
        rec.is_read = True

    await db.commit()
    return {"marked_read": len(recs)}


@router.post("/{farm_id}/feedback/{recommendation_id}")
async def submit_recommendation_feedback(
    farm_id: int,
    recommendation_id: int,
    feedback: FeedbackRequest,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """
    Save farmer feedback on a recommendation (helpful or not).
    This feedback is used by the continual learning system to improve recommendation accuracy.
    Request body: {"helpful": true/false}
    """

    await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    result = await db.execute(
        select(Recommendation).where(
            Recommendation.id == recommendation_id,
            Recommendation.farm_id == farm_id,
        )
    )
    rec = result.scalar_one_or_none()
    if not rec:
        raise HTTPException(status_code=404, detail="Recommendation not found")

    # Save feedback and timestamp
    rec.helpful = feedback.helpful
    rec.feedback_at = datetime.now(timezone.utc)

    await db.commit()
    await db.refresh(rec)

    # Update FeedbackLearningBridge to recalculate recommendation accuracy
    try:
        from src.ml.feedback_integration import FeedbackLearningBridge
        bridge = FeedbackLearningBridge(db)
        accuracy = await bridge.calculate_feedback_accuracy(farm_id, days=7)
        print(f"[Feedback] Recommendation {recommendation_id}: {'helpful' if feedback.helpful else 'not helpful'}")
        print(f"[Stats] Farm {farm_id}: accuracy = {accuracy['overall_accuracy']:.1f}%")
    except Exception as e:
        print(f"[Warning] Feedback logging error: {e}")

    return {
        "id": rec.id,
        "helpful": rec.helpful,
        "feedback_at": rec.feedback_at.isoformat() if rec.feedback_at else None,
        "message": "Feedback recorded successfully"
    }


@router.get("/{farm_id}/feedback-stats")
async def get_feedback_stats(
    farm_id: int,
    days: int = 7,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """
    Returns feedback accuracy statistics for recommendations over the last N days.
    Useful for measuring model improvement over time.
    """
    await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    # Calculate the start of the stats window
    since = datetime.now(timezone.utc) - timedelta(days=days)

    # إجمالي التوصيات مع فيدباك
    result = await db.execute(
        select(
            func.count(Recommendation.id).label("total"),
            func.sum(func.cast(Recommendation.helpful, Integer)).label("helpful_count"),
            func.count(
                Recommendation.id
            ).filter(Recommendation.helpful == False).label("not_helpful_count")  # noqa: E712
        ).where(
            Recommendation.farm_id == farm_id,
            Recommendation.helpful.isnot(None),
            Recommendation.feedback_at >= since
        )
    )

    row = result.scalar_one()
    total = row.total or 0
    helpful = row.helpful_count or 0
    not_helpful = row.not_helpful_count or 0

    accuracy = (helpful / total * 100) if total > 0 else 0

    return {
        "days": days,
        "total_feedback": total,
        "helpful": helpful,
        "not_helpful": not_helpful,
        "accuracy_percentage": round(accuracy, 2),
        "pending_feedback": "Number of recommendations not yet rated by the farmer"
    }


async def _get_farm_or_404(farm_id: int, user_id: int, db: AsyncSession) -> Farm:
    """Fetch farm by ID and verify ownership. Raises 404 if not found or not owned by user."""
    result = await db.execute(
        select(Farm).where(Farm.id == farm_id, Farm.user_id == user_id)
    )
    farm = result.scalar_one_or_none()
    if not farm:
        raise HTTPException(status_code=404, detail="Farm not found")
    return farm


def _normalize_category(value: Optional[str]) -> str:
    raw = (value or "general").lower()
    if raw in ("air_temperature", "temperature", "climate"):
        return "temperature"
    if raw in ("air_humidity", "humidity"):
        return "humidity"
    if raw in ("soil_temperature", "soil"):
        return "soil"
    if raw in ("soil_moisture", "irrigation", "water"):
        return "irrigation"
    return raw


def _recommendation_execution_intent(rec: Recommendation, category: str) -> Optional[dict]:
    text = f"{rec.message or ''} {rec.reasoning or ''}".lower()

    if category in {"irrigation", "soil"}:
        has_irrigation_intent = (
            category == "irrigation"
            or "ري" in text
            or "irrigat" in text
            or "رطوبة التربة" in text
            or "soil moisture" in text
        )
        if not has_irrigation_intent:
            return None

        if any(token in text for token in ("مؤجل", "السلامة", "لا تسمح", "deferred", "safety")):
            return {
                "category": "irrigation",
                "decision": {
                    "action": "hold",
                    "reason": "Recommendation is safety-blocked and should not be executed manually.",
                    "source": "recommendation_intent",
                },
            }

        stop_tokens = ("تقليل", "إيقاف", "ايقاف", "أوقف", "اوقف", "reduce", "stop", "above", "أعلى")
        action = "stop" if any(token in text for token in stop_tokens) else "start"
        return {
            "category": "irrigation",
            "decision": {
                "action": action,
                "reason": rec.reasoning or rec.message,
                "source": "recommendation_intent",
            },
        }

    if category == "temperature":
        if any(token in text for token in ("تبريد", "حرارة", "cool", "temperature")):
            return {
                "category": "temperature",
                "decision": {
                    "action": "cooling_full",
                    "reason": rec.reasoning or rec.message,
                    "source": "recommendation_intent",
                },
            }

    if category == "humidity":
        if any(token in text for token in ("تهوية", "رطوبة", "fan", "ventilat", "humidity")):
            return {
                "category": "humidity",
                "decision": {
                    "action": "fan_only",
                    "reason": rec.reasoning or rec.message,
                    "source": "recommendation_intent",
                },
            }

    return None


def _recommendation_saved_execution_action(rec: Recommendation, category: str) -> Optional[dict]:
    decision = getattr(rec, "execution_action", None)
    if not isinstance(decision, dict):
        return None

    action = decision.get("action")
    if action in {"start", "stop"}:
        return {"category": "irrigation", "decision": decision}
    if action in {"cooling_full", "fan_only", "stop"}:
        return {
            "category": "humidity" if category == "humidity" else "temperature",
            "decision": decision,
        }
    return None


def _recommendation_reading_mismatch_reason(
    rec: Recommendation,
    sensor_data: dict,
    category: str,
) -> Optional[str]:
    sensor_type = {
        "irrigation": "soil_moisture",
        "humidity": "air_humidity",
        "temperature": "air_temperature",
    }.get(category)
    if not sensor_type:
        return None

    current_value = sensor_data.get(sensor_type)
    if current_value is None:
        return None

    recommendation_value = _extract_recommendation_sensor_value(rec, sensor_type)
    if recommendation_value is None:
        return None

    current_value = float(current_value)
    tolerance = 3.0 if sensor_type == "air_temperature" else 8.0
    if abs(current_value - recommendation_value) <= tolerance:
        return None

    unit = "°C" if sensor_type == "air_temperature" else "%"
    suffix = " لا يتطلب هذا السجل أمر جهاز الآن، وسيعتمد النظام على أحدث توصية عند وصول قراءة جديدة."
    if sensor_type == "soil_moisture":
        return (
            f"لم يتم تشغيل الري لأن رطوبة التربة تغيّرت من {recommendation_value:.1f}{unit} "
            f"إلى {current_value:.1f}{unit}.{suffix}"
        )
    if sensor_type == "air_humidity":
        return (
            f"لم يتم تشغيل التهوية لأن رطوبة الهواء تغيّرت من {recommendation_value:.1f}{unit} "
            f"إلى {current_value:.1f}{unit}.{suffix}"
        )
    return (
        f"لم يتم تشغيل التبريد لأن حرارة الهواء تغيّرت من {recommendation_value:.1f}{unit} "
        f"إلى {current_value:.1f}{unit}.{suffix}"
    )


def _extract_recommendation_sensor_value(rec: Recommendation, sensor_type: str) -> Optional[float]:
    text = f"{rec.message or ''} {rec.reasoning or ''}"
    patterns = {
        "soil_moisture": [
            r"رطوبة\s+التربة(?:\s+الحالية)?\s*\(?\s*(\d+(?:\.\d+)?)\s*%?",
            r"soil\s+moisture[^\d]{0,30}(\d+(?:\.\d+)?)\s*%?",
        ],
        "air_humidity": [
            r"رطوبة\s+الهواء(?:\s+الحالية| داخل المحمية)?\s*\(?\s*(\d+(?:\.\d+)?)\s*%?",
            r"air\s+humidity[^\d]{0,30}(\d+(?:\.\d+)?)\s*%?",
        ],
        "air_temperature": [
            r"درجة\s+الحرارة(?:\s+الداخلية|\s+الحالية)?\s*\(?\s*(\d+(?:\.\d+)?)\s*°?\s*C?",
            r"حرارة\s+الهواء[^\d]{0,30}(\d+(?:\.\d+)?)\s*°?",
            r"temperature[^\d]{0,30}(\d+(?:\.\d+)?)\s*°?\s*C?",
        ],
    }.get(sensor_type, [])

    for pattern in patterns:
        match = re.search(pattern, text, flags=re.IGNORECASE)
        if match:
            try:
                return float(match.group(1))
            except (TypeError, ValueError):
                return None
    return None


async def _latest_sensor_snapshot(farm_id: int, db: AsyncSession) -> dict:
    snapshot = {}
    for sensor_type in ("soil_moisture", "soil_temperature", "air_temperature", "air_humidity", "light_intensity"):
        result = await db.execute(
            select(SensorReading)
            .where(SensorReading.farm_id == farm_id, SensorReading.sensor_type == sensor_type)
            .order_by(desc(SensorReading.timestamp))
            .limit(1)
        )
        reading = result.scalar_one_or_none()
        if reading is not None:
            snapshot[sensor_type] = reading.value
    return snapshot


async def _execute_climate_decision(
    *,
    db: AsyncSession,
    farm_id: int,
    recommendation_id: int,
    decision: dict,
    is_auto: bool,
) -> dict:
    action = decision.get("action")
    fan_state = action in {"cooling_full", "fan_only"}
    cooler_state = action == "cooling_full"
    mode = "full" if fan_state and cooler_state else "fan_only" if fan_state else "stop"
    command_payload = {
        "fan": fan_state,
        "cooler": cooler_state,
        "recommendation_id": recommendation_id,
        "decision": decision,
    }
    fan_device_id = _climate_device_id(farm_id, "fan")
    cooling_device_id = _climate_device_id(farm_id, "cooling")

    db.add(DeviceCommand(
        device_id=fan_device_id,
        command="FAN_ON" if fan_state else "FAN_OFF",
        payload=json.dumps(command_payload),
        status="pending",
        issued_at=datetime.now(timezone.utc),
    ))
    db.add(DeviceCommand(
        device_id=cooling_device_id,
        command="COOLER_ON" if cooler_state else "COOLER_OFF",
        payload=json.dumps(command_payload),
        status="pending",
        issued_at=datetime.now(timezone.utc),
    ))
    db.add(ActivityLog(
        farm_id=farm_id,
        action_type=f"{'auto' if is_auto else 'manual'}_cooling_{mode}",
        device_id=cooling_device_id if cooler_state else fan_device_id,
        details={
            "mode": mode,
            "fan": fan_state,
            "cooler": cooler_state,
            "triggered_by": "automation" if is_auto else "user",
            "recommendation_id": recommendation_id,
            "decision_source": decision.get("source"),
            "decision_confidence": decision.get("confidence"),
            "reason": decision.get("reason"),
            "targets": decision.get("targets"),
        },
        performed_by="system" if is_auto else "user",
    ))

    tuya_sent = False
    if tuya_client.is_tuya_farm(farm_id):
        if cooler_state:
            tuya_sent = await asyncio.to_thread(tuya_client.control_cooling, True)
        elif fan_state:
            await asyncio.to_thread(tuya_client.control_cooler_only, False)
            tuya_sent = await asyncio.to_thread(tuya_client.control_fan, True)
        else:
            await asyncio.to_thread(tuya_client.control_cooling, False)
            tuya_sent = await asyncio.to_thread(tuya_client.control_fan, False)
        if not tuya_sent:
            raise HTTPException(
                status_code=502,
                detail="تعذر إرسال أمر المناخ إلى جهاز Tuya. تحقق من اتصال الجهاز ثم حاول مرة أخرى.",
            )

    return {
        "action": action,
        "mode": mode,
        "fan": fan_state,
        "cooler": cooler_state,
        "tuya_sent": tuya_sent,
    }


async def _execute_irrigation_decision(
    *,
    db: AsyncSession,
    farm_id: int,
    recommendation_id: int,
    decision: dict,
    duration_min: int,
    is_auto: bool,
) -> dict:
    action = decision.get("action")
    valve_state = action == "start"
    if valve_state:
        farm_result = await db.execute(select(Farm).where(Farm.id == farm_id).limit(1))
        farm = farm_result.scalar_one_or_none()
        current_level = float(getattr(farm, "current_water_level", 0.0) or 0.0)
        capacity = float(getattr(farm, "water_tank_capacity", 0.0) or 0.0)
        tank_pct = (current_level / capacity) * 100 if capacity > 0 else 0.0
        if current_level <= 10 or tank_pct <= 5:
            raise HTTPException(
                status_code=422,
                detail=(
                    f"تعذر تشغيل مضخة الري لأن مستوى خزان المياه منخفض ({tank_pct:.1f}%). "
                    "يرجى إعادة تعبئة الخزان أو انتظار إعادة التعبئة في المحاكي."
                ),
            )

    device_id = _irrigation_device_id_for_farm(farm_id)
    actuator = await _get_or_create_irrigation_actuator(farm_id, device_id, db)
    actuator.state = "on" if valve_state else "off"

    existing = await db.execute(
        select(IrrigationEvent)
        .join(IrrigationCommand)
        .where(
            IrrigationCommand.actuator_id == actuator.id,
            IrrigationEvent.status == IrrigationStatus.active,
        )
        .limit(1)
    )
    existing_event = existing.scalar_one_or_none()
    if existing_event:
        existing_event.status = IrrigationStatus.completed

    if valve_state:
        command = IrrigationCommand(
            actuator_id=actuator.id,
            mode=IrrigationMode.auto if is_auto else IrrigationMode.manual,
            duration_min=duration_min,
        )
        db.add(command)
        await db.flush()
        db.add(IrrigationEvent(
            command_id=command.id,
            status=IrrigationStatus.active,
        ))

    command_payload = {
        "valve": valve_state,
        "duration_min": duration_min,
        "recommendation_id": recommendation_id,
        "decision": decision,
    }

    db.add(DeviceCommand(
        device_id=device_id,
        command="VALVE_OPEN" if valve_state else "VALVE_CLOSE",
        payload=json.dumps(command_payload),
        status="pending",
        issued_at=datetime.now(timezone.utc),
    ))
    db.add(ActivityLog(
        farm_id=farm_id,
        action_type=f"{'auto' if is_auto else 'manual'}_irrigation_{'start' if valve_state else 'stop'}",
        device_id=device_id,
        details={
            "valve": valve_state,
            "duration_min": duration_min,
            "triggered_by": "automation" if is_auto else "user",
            "recommendation_id": recommendation_id,
            "decision_source": decision.get("source"),
            "decision_confidence": decision.get("confidence"),
            "reason": decision.get("reason"),
            "targets": decision.get("targets"),
        },
        performed_by="system" if is_auto else "user",
    ))

    tuya_sent = False
    if tuya_client.is_tuya_farm(farm_id):
        tuya_sent = await asyncio.to_thread(tuya_client.control_irrigation, valve_state)
        if not tuya_sent:
            raise HTTPException(
                status_code=502,
                detail="تعذر إرسال أمر الري إلى جهاز Tuya. تحقق من اتصال الجهاز ثم حاول مرة أخرى.",
            )

    return {
        "action": action,
        "valve": valve_state,
        "duration_min": duration_min,
        "tuya_sent": tuya_sent,
    }


async def _get_or_create_irrigation_actuator(farm_id: int, device_id: str, db: AsyncSession) -> Actuator:
    result = await db.execute(select(Device).where(Device.device_id == device_id).limit(1))
    device = result.scalar_one_or_none()
    if device is None:
        device = Device(
            farm_id=farm_id,
            device_id=device_id,
            name="Irrigation Valve",
            type="actuator",
        )
        db.add(device)
        await db.flush()
    elif device.farm_id != farm_id:
        raise HTTPException(status_code=409, detail="Device belongs to a different farm")

    result = await db.execute(select(Actuator).where(Actuator.device_id == device_id).limit(1))
    actuator = result.scalar_one_or_none()
    if actuator is None:
        actuator = Actuator(
            device_id=device_id,
            actuator_type="irrigation_valve",
            state="off",
            power_rating_kw=0.5,
        )
        db.add(actuator)
        await db.flush()

    return actuator


def _irrigation_device_id_for_farm(farm_id: int) -> str:
    if tuya_client.is_tuya_farm(farm_id):
        return tuya_client.get_tuya_actuator_device_id("irrigation") or f"tuya_irrigation_{farm_id}"
    return f"irrigation_{farm_id}"


def _climate_device_id(farm_id: int, kind: str) -> str:
    simulator_id = f"fan_unit_{farm_id}" if kind == "fan" else f"cooling_unit_{farm_id}"
    return tuya_client.get_farm_actuator_device_id(farm_id, kind, simulator_id)
