# backend/src/api/routes/recommendations.py
"""
Recommendations Routes — Warif API
=====================================
Handles AI-generated recommendation endpoints:
  - GET  /{farm_id}                              : list recommendations with filters
  - POST /{farm_id}/mark-read/{id}               : mark a recommendation as read
  - POST /{farm_id}/mark-all-read                : mark all recommendations as read
  - POST /{farm_id}/feedback/{id}                : submit helpful/not helpful feedback
  - GET  /{farm_id}/feedback-stats               : get feedback accuracy statistics

Recommendations are generated by the Decision Engine on every sensor reading.
All endpoints require JWT authentication and farm ownership verification.
"""
import asyncio
import json
from typing import List, Optional
from datetime import datetime, timezone, timedelta
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc, Integer, func
from pydantic import BaseModel

from src.db.session import get_db
from src.db.models.models import (
    Recommendation, Farm, ActivityLog, SensorReading, DeviceCommand,
    Device, Actuator, IrrigationCommand, IrrigationEvent, IrrigationMode,
    IrrigationStatus,
)
from src.api.schemas.schemas import RecommendationOut
from src.core.security import get_current_user
from src.services import tuya_client
from src.services.decision_engine import get_engine
from src.services.recommendation_suppression import get_current_decision_state
# PresentationFormatter removed — formatting is handled inline per endpoint


class FeedbackRequest(BaseModel):
    # Request body for recommendation feedback — farmer rates if recommendation was useful
    helpful: bool


class RecommendationActionRequest(BaseModel):
    status: str


class ExecuteRecommendationRequest(BaseModel):
    mode: str = "manual"
    duration_min: int = 15


router = APIRouter()


# Returns filtered recommendations for a farm — supports category, severity, type, and unread filters
@router.get("/{farm_id}", response_model=List[dict])
async def list_recommendations(
    farm_id: int,
    category: Optional[str] = Query(None, description="irrigation | temperature | humidity | soil | general"),
    severity: Optional[str] = Query(None, description="normal | warning | urgent"),
    type: Optional[str] = Query(None, description="urgent | improvement"),
    since: Optional[datetime] = Query(None, description="Return recommendations created at or after this UTC timestamp"),
    unread_only: bool = Query(False),
    limit: int = Query(50, le=1000),
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """List recommendations for a farm, filterable by category, severity, and type."""
    await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    q = (
        select(Recommendation)
        .where(Recommendation.farm_id == farm_id)
        .order_by(desc(Recommendation.created_at))
        .limit(limit)
    )
    if category:
        q = q.where(Recommendation.category == category)
    if severity:
        q = q.where(Recommendation.severity == severity)
    if since:
        since_utc = since if since.tzinfo else since.replace(tzinfo=timezone.utc)
        q = q.where(Recommendation.created_at >= since_utc)
    if type == "urgent":
        q = q.where((Recommendation.is_alert == True) | (Recommendation.severity.in_(["urgent", "warning"])))  # noqa: E712
    elif type == "improvement":
        q = q.where((Recommendation.is_alert == False) & (Recommendation.severity == "normal"))  # noqa: E712
    if unread_only:
        q = q.where(Recommendation.is_read == False)  # noqa: E712

    result = await db.execute(q)
    recommendations = result.scalars().all()
    recommendation_ids = {rec.id for rec in recommendations}

    action_status_by_id = {}
    if recommendation_ids:
        action_logs_result = await db.execute(
            select(ActivityLog)
            .where(
                ActivityLog.farm_id == farm_id,
                ActivityLog.action_type == "recommendation_executed",
            )
            .order_by(desc(ActivityLog.created_at))
            .limit(1000)
        )
        for log in action_logs_result.scalars().all():
            details = log.details or {}
            try:
                rec_id = int(details.get("recommendation_id"))
            except (TypeError, ValueError):
                continue
            if rec_id in recommendation_ids and rec_id not in action_status_by_id:
                action_status_by_id[rec_id] = "executed"

    def normalize_category(value: Optional[str]) -> str:
        raw = (value or "general").lower()
        if raw in ("air_temperature", "temperature", "climate"):
            return "temperature"
        if raw in ("air_humidity", "humidity"):
            return "humidity"
        if raw in ("soil_temperature", "soil"):
            return "soil"
        if raw in ("soil_moisture", "irrigation", "water"):
            return "irrigation"
        return raw

    # Serialize recommendations — safely extract enum values for frontend
    def infer_source_sensor_type(category_value: str, message: Optional[str], reasoning: Optional[str]) -> Optional[str]:
        text = f"{message or ''} {reasoning or ''}".lower()
        if category_value == "temperature":
            return "air_temperature"
        if category_value == "humidity":
            return "air_humidity"
        if category_value == "soil":
            return "soil_temperature"
        if category_value == "irrigation":
            if "soil" in text or "تربة" in text or "رطوبة التربة" in text:
                return "soil_moisture"
            return "water_usage"
        return None

    professional_recs = []
    for rec in recommendations:
        try:
            # Safely extract enum string values for category and severity
            category_value = rec.category.value if hasattr(rec.category, 'value') else str(rec.category)
            severity_value = rec.severity.value if hasattr(rec.severity, 'value') else str(rec.severity)
            normalized_category = normalize_category(category_value)
            action_status = rec.mode if rec.mode in ("executed", "ignored") else action_status_by_id.get(rec.id)
            decision_state = await get_current_decision_state(
                db=db,
                farm_id=farm_id,
                category=normalized_category,
                message=rec.message,
                created_at=rec.created_at,
            )
            if action_status == "executed" and decision_state.get("state") == "hold":
                decision_state = {
                    **decision_state,
                    "state": "completed",
                    "label": "تم التنفيذ",
                    "label_en": "Completed",
                    "reason": "تم تنفيذ التوصية ولا يوجد إجراء نشط حاليا.",
                    "reason_en": "The recommendation was executed and no action is active now.",
                }

            professional_recs.append({
                "id": rec.id,
                "source": "recommendation",
                "title": rec.message[:60] if rec.message else "توصية",
                "message": rec.message,
                "reasoning": rec.reasoning,
                "category": normalized_category,
                "source_sensor_type": infer_source_sensor_type(normalized_category, rec.message, rec.reasoning),
                "severity": severity_value,
                "is_read": rec.is_read,
                "is_alert": rec.is_alert,
                "helpful": rec.helpful,
                "feedback_at": rec.feedback_at.isoformat() if rec.feedback_at else None,
                "action_status": action_status,
                "decision_state": decision_state,
                "created_at": rec.created_at.isoformat() if rec.created_at else None,
            })
        except Exception as e:
            print(f"[ERROR] Recommendation {rec.id}: {e}")
            continue

    professional_recs.sort(key=lambda item: item.get("created_at") or "", reverse=True)
    professional_recs = professional_recs[:limit]

    return professional_recs


@router.post("/{farm_id}/action/{recommendation_id}", response_model=dict)
async def record_recommendation_action(
    farm_id: int,
    recommendation_id: int,
    action: RecommendationActionRequest,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """Persist the user's execute/ignore decision for a recommendation."""
    await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    result = await db.execute(
        select(Recommendation).where(
            Recommendation.id == recommendation_id,
            Recommendation.farm_id == farm_id,
        )
    )
    rec = result.scalar_one_or_none()
    if not rec:
        raise HTTPException(status_code=404, detail="Recommendation not found")

    status = action.status.strip().lower()
    if status not in ("executed", "ignored"):
        raise HTTPException(status_code=422, detail="status must be executed or ignored")

    if status == "executed":
        log = ActivityLog(
            farm_id=farm_id,
            user_id=int(current_user["sub"]),
            action_type="recommendation_executed",
            details={
                "recommendation_id": recommendation_id,
                "category": rec.category.value if hasattr(rec.category, "value") else str(rec.category),
                "message": rec.message,
            },
            performed_by="user",
        )
        db.add(log)
    rec.is_read = True
    rec.mode = status
    await db.commit()

    return {
        "success": True,
        "recommendation_id": recommendation_id,
        "action_status": status,
    }


@router.post("/{farm_id}/execute/{recommendation_id}", response_model=dict)
async def execute_recommendation(
    farm_id: int,
    recommendation_id: int,
    body: ExecuteRecommendationRequest = ExecuteRecommendationRequest(),
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """Execute a recommendation through the current Decision Engine action contract."""
    farm = await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    result = await db.execute(
        select(Recommendation).where(
            Recommendation.id == recommendation_id,
            Recommendation.farm_id == farm_id,
        )
    )
    rec = result.scalar_one_or_none()
    if not rec:
        raise HTTPException(status_code=404, detail="Recommendation not found")

    sensor_data = await _latest_sensor_snapshot(farm_id, db)
    sensor_data["crop_type"] = farm.crop_type or "tomatoes"

    engine = get_engine()
    report = await engine.analyze_with_intelligence(sensor_data, farm_id)
    category = _normalize_category(rec.category.value if hasattr(rec.category, "value") else str(rec.category))
    if category not in {"irrigation", "temperature", "humidity"}:
        raise HTTPException(status_code=422, detail=f"Recommendation category '{category}' is not directly executable")

    domain = "irrigation" if category == "irrigation" else "climate"
    decision = report.get("action_decisions", {}).get(domain)
    if not decision:
        raise HTTPException(status_code=422, detail="No executable decision is available for this recommendation")
    if decision.get("action") == "hold":
        return {
            "success": True,
            "executed": False,
            "recommendation_id": recommendation_id,
            "domain": domain,
            "decision": decision,
            "result": {"action": "hold", "reason": decision.get("reason")},
        }

    mode = (body.mode or "manual").lower()
    is_auto = mode == "auto"
    if domain == "irrigation":
        result_payload = await _execute_irrigation_decision(
            db=db,
            farm_id=farm_id,
            recommendation_id=recommendation_id,
            decision=decision,
            duration_min=body.duration_min,
            is_auto=is_auto,
        )
    else:
        result_payload = await _execute_climate_decision(
            db=db,
            farm_id=farm_id,
            recommendation_id=recommendation_id,
            decision=decision,
            is_auto=is_auto,
        )

    rec.is_read = True
    rec.mode = "executed"
    db.add(ActivityLog(
        farm_id=farm_id,
        user_id=int(current_user["sub"]),
        action_type="recommendation_executed",
        details={
            "recommendation_id": recommendation_id,
            "category": category,
            "domain": domain,
            "decision": decision,
            "result": result_payload,
        },
        performed_by="system" if is_auto else "user",
    ))
    await db.commit()

    return {
        "success": True,
        "recommendation_id": recommendation_id,
        "domain": domain,
        "decision": decision,
        "result": result_payload,
    }


@router.post("/{farm_id}/mark-read/{recommendation_id}", response_model=RecommendationOut)
async def mark_as_read(
    farm_id: int,
    recommendation_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """Mark a recommendation as read."""
    await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    result = await db.execute(
        select(Recommendation).where(
            Recommendation.id == recommendation_id,
            Recommendation.farm_id == farm_id,
        )
    )
    rec = result.scalar_one_or_none()
    if not rec:
        raise HTTPException(status_code=404, detail="Recommendation not found")

    rec.is_read = True
    await db.commit()
    await db.refresh(rec)
    return rec


@router.post("/{farm_id}/mark-all-read", response_model=dict)
async def mark_all_read(
    farm_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """Mark all recommendations for a farm as read."""
    await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    result = await db.execute(
        select(Recommendation).where(
            Recommendation.farm_id == farm_id,
            Recommendation.is_read == False,  # noqa: E712
        )
    )
    recs = result.scalars().all()
    for rec in recs:
        rec.is_read = True

    await db.commit()
    return {"marked_read": len(recs)}


@router.post("/{farm_id}/feedback/{recommendation_id}")
async def submit_recommendation_feedback(
    farm_id: int,
    recommendation_id: int,
    feedback: FeedbackRequest,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """
    Save farmer feedback on a recommendation (helpful or not).
    This feedback is used by the continual learning system to improve recommendation accuracy.
    Request body: {"helpful": true/false}
    """

    await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    result = await db.execute(
        select(Recommendation).where(
            Recommendation.id == recommendation_id,
            Recommendation.farm_id == farm_id,
        )
    )
    rec = result.scalar_one_or_none()
    if not rec:
        raise HTTPException(status_code=404, detail="Recommendation not found")

    # Save feedback and timestamp
    rec.helpful = feedback.helpful
    rec.feedback_at = datetime.now(timezone.utc)

    await db.commit()
    await db.refresh(rec)

    # Update FeedbackLearningBridge to recalculate recommendation accuracy
    try:
        from src.ml.feedback_integration import FeedbackLearningBridge
        bridge = FeedbackLearningBridge(db)
        accuracy = await bridge.calculate_feedback_accuracy(farm_id, days=7)
        print(f"[Feedback] Recommendation {recommendation_id}: {'helpful' if feedback.helpful else 'not helpful'}")
        print(f"[Stats] Farm {farm_id}: accuracy = {accuracy['overall_accuracy']:.1f}%")
    except Exception as e:
        print(f"[Warning] Feedback logging error: {e}")

    return {
        "id": rec.id,
        "helpful": rec.helpful,
        "feedback_at": rec.feedback_at.isoformat() if rec.feedback_at else None,
        "message": "Feedback recorded successfully"
    }


@router.get("/{farm_id}/feedback-stats")
async def get_feedback_stats(
    farm_id: int,
    days: int = 7,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """
    Returns feedback accuracy statistics for recommendations over the last N days.
    Useful for measuring model improvement over time.
    """
    await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    # Calculate the start of the stats window
    since = datetime.now(timezone.utc) - timedelta(days=days)

    # إجمالي التوصيات مع فيدباك
    result = await db.execute(
        select(
            func.count(Recommendation.id).label("total"),
            func.sum(func.cast(Recommendation.helpful, Integer)).label("helpful_count"),
            func.count(
                Recommendation.id
            ).filter(Recommendation.helpful == False).label("not_helpful_count")  # noqa: E712
        ).where(
            Recommendation.farm_id == farm_id,
            Recommendation.helpful.isnot(None),
            Recommendation.feedback_at >= since
        )
    )

    row = result.scalar_one()
    total = row.total or 0
    helpful = row.helpful_count or 0
    not_helpful = row.not_helpful_count or 0

    accuracy = (helpful / total * 100) if total > 0 else 0

    return {
        "days": days,
        "total_feedback": total,
        "helpful": helpful,
        "not_helpful": not_helpful,
        "accuracy_percentage": round(accuracy, 2),
        "pending_feedback": "Number of recommendations not yet rated by the farmer"
    }


async def _get_farm_or_404(farm_id: int, user_id: int, db: AsyncSession) -> Farm:
    """Fetch farm by ID and verify ownership. Raises 404 if not found or not owned by user."""
    result = await db.execute(
        select(Farm).where(Farm.id == farm_id, Farm.user_id == user_id)
    )
    farm = result.scalar_one_or_none()
    if not farm:
        raise HTTPException(status_code=404, detail="Farm not found")
    return farm


def _normalize_category(value: Optional[str]) -> str:
    raw = (value or "general").lower()
    if raw in ("air_temperature", "temperature", "climate"):
        return "temperature"
    if raw in ("air_humidity", "humidity"):
        return "humidity"
    if raw in ("soil_temperature", "soil"):
        return "soil"
    if raw in ("soil_moisture", "irrigation", "water"):
        return "irrigation"
    return raw


async def _latest_sensor_snapshot(farm_id: int, db: AsyncSession) -> dict:
    snapshot = {}
    for sensor_type in ("soil_moisture", "soil_temperature", "air_temperature", "air_humidity", "light_intensity"):
        result = await db.execute(
            select(SensorReading)
            .where(SensorReading.farm_id == farm_id, SensorReading.sensor_type == sensor_type)
            .order_by(desc(SensorReading.timestamp))
            .limit(1)
        )
        reading = result.scalar_one_or_none()
        if reading is not None:
            snapshot[sensor_type] = reading.value
    return snapshot


async def _execute_climate_decision(
    *,
    db: AsyncSession,
    farm_id: int,
    recommendation_id: int,
    decision: dict,
    is_auto: bool,
) -> dict:
    action = decision.get("action")
    fan_state = action in {"cooling_full", "fan_only"}
    cooler_state = action == "cooling_full"
    mode = "full" if fan_state and cooler_state else "fan_only" if fan_state else "stop"
    command_payload = {
        "fan": fan_state,
        "cooler": cooler_state,
        "recommendation_id": recommendation_id,
        "decision": decision,
    }

    db.add(DeviceCommand(
        device_id=f"fan_unit_{farm_id}",
        command="FAN_ON" if fan_state else "FAN_OFF",
        payload=json.dumps(command_payload),
        status="pending",
        issued_at=datetime.now(timezone.utc),
    ))
    db.add(DeviceCommand(
        device_id=f"cooling_unit_{farm_id}",
        command="COOLER_ON" if cooler_state else "COOLER_OFF",
        payload=json.dumps(command_payload),
        status="pending",
        issued_at=datetime.now(timezone.utc),
    ))
    db.add(ActivityLog(
        farm_id=farm_id,
        action_type=f"{'auto' if is_auto else 'manual'}_cooling_{mode}",
        device_id=f"fan_unit_{farm_id}",
        details={
            "mode": mode,
            "fan": fan_state,
            "cooler": cooler_state,
            "triggered_by": "automation" if is_auto else "user",
            "recommendation_id": recommendation_id,
            "decision_source": decision.get("source"),
            "decision_confidence": decision.get("confidence"),
            "reason": decision.get("reason"),
            "targets": decision.get("targets"),
        },
        performed_by="system" if is_auto else "user",
    ))

    tuya_sent = False
    if tuya_client.is_tuya_farm(farm_id):
        if cooler_state:
            tuya_sent = await asyncio.to_thread(tuya_client.control_cooling, True)
        elif fan_state:
            await asyncio.to_thread(tuya_client.control_cooler_only, False)
            tuya_sent = await asyncio.to_thread(tuya_client.control_fan, True)
        else:
            await asyncio.to_thread(tuya_client.control_cooling, False)
            tuya_sent = await asyncio.to_thread(tuya_client.control_fan, False)

    return {
        "action": action,
        "mode": mode,
        "fan": fan_state,
        "cooler": cooler_state,
        "tuya_sent": tuya_sent,
    }


async def _execute_irrigation_decision(
    *,
    db: AsyncSession,
    farm_id: int,
    recommendation_id: int,
    decision: dict,
    duration_min: int,
    is_auto: bool,
) -> dict:
    action = decision.get("action")
    valve_state = action == "start"
    device_id = _irrigation_device_id_for_farm(farm_id)
    actuator = await _get_or_create_irrigation_actuator(farm_id, device_id, db)
    actuator.state = "on" if valve_state else "off"

    existing = await db.execute(
        select(IrrigationEvent)
        .join(IrrigationCommand)
        .where(
            IrrigationCommand.actuator_id == actuator.id,
            IrrigationEvent.status == IrrigationStatus.active,
        )
        .limit(1)
    )
    existing_event = existing.scalar_one_or_none()
    if existing_event:
        existing_event.status = IrrigationStatus.completed

    if valve_state:
        command = IrrigationCommand(
            actuator_id=actuator.id,
            mode=IrrigationMode.auto if is_auto else IrrigationMode.manual,
            duration_min=duration_min,
        )
        db.add(command)
        await db.flush()
        db.add(IrrigationEvent(
            command_id=command.id,
            status=IrrigationStatus.active,
        ))

    command_payload = {
        "valve": valve_state,
        "duration_min": duration_min,
        "recommendation_id": recommendation_id,
        "decision": decision,
    }

    db.add(DeviceCommand(
        device_id=device_id,
        command="VALVE_OPEN" if valve_state else "VALVE_CLOSE",
        payload=json.dumps(command_payload),
        status="pending",
        issued_at=datetime.now(timezone.utc),
    ))
    db.add(ActivityLog(
        farm_id=farm_id,
        action_type=f"{'auto' if is_auto else 'manual'}_irrigation_{'start' if valve_state else 'stop'}",
        device_id=device_id,
        details={
            "valve": valve_state,
            "duration_min": duration_min,
            "triggered_by": "automation" if is_auto else "user",
            "recommendation_id": recommendation_id,
            "decision_source": decision.get("source"),
            "decision_confidence": decision.get("confidence"),
            "reason": decision.get("reason"),
            "targets": decision.get("targets"),
        },
        performed_by="system" if is_auto else "user",
    ))

    tuya_sent = False
    if tuya_client.is_tuya_farm(farm_id):
        tuya_sent = await asyncio.to_thread(tuya_client.control_irrigation, valve_state)

    return {
        "action": action,
        "valve": valve_state,
        "duration_min": duration_min,
        "tuya_sent": tuya_sent,
    }


async def _get_or_create_irrigation_actuator(farm_id: int, device_id: str, db: AsyncSession) -> Actuator:
    result = await db.execute(select(Device).where(Device.device_id == device_id).limit(1))
    device = result.scalar_one_or_none()
    if device is None:
        device = Device(
            farm_id=farm_id,
            device_id=device_id,
            name="Irrigation Valve",
            type="actuator",
        )
        db.add(device)
        await db.flush()
    elif device.farm_id != farm_id:
        raise HTTPException(status_code=409, detail="Device belongs to a different farm")

    result = await db.execute(select(Actuator).where(Actuator.device_id == device_id).limit(1))
    actuator = result.scalar_one_or_none()
    if actuator is None:
        actuator = Actuator(
            device_id=device_id,
            actuator_type="irrigation_valve",
            state="off",
            power_rating_kw=0.5,
        )
        db.add(actuator)
        await db.flush()

    return actuator


def _irrigation_device_id_for_farm(farm_id: int) -> str:
    if tuya_client.is_tuya_farm(farm_id):
        return tuya_client.get_tuya_actuator_device_id("irrigation") or f"tuya_irrigation_{farm_id}"
    return f"irrigation_{farm_id}"
