# backend/src/api/routes/recommendations.py
"""
Recommendations Routes — Warif API
=====================================
Handles AI-generated recommendation endpoints:
  - GET  /{farm_id}                              : list recommendations with filters
  - POST /{farm_id}/mark-read/{id}               : mark a recommendation as read
  - POST /{farm_id}/mark-all-read                : mark all recommendations as read
  - POST /{farm_id}/feedback/{id}                : submit helpful/not helpful feedback
  - GET  /{farm_id}/feedback-stats               : get feedback accuracy statistics

Recommendations are generated by the Decision Engine on every sensor reading.
All endpoints require JWT authentication and farm ownership verification.
"""
from typing import List, Optional
from datetime import datetime, timezone, timedelta
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc, Integer, func
from pydantic import BaseModel

from src.db.session import get_db
from src.db.models.models import Recommendation, Farm
from src.api.schemas.schemas import RecommendationOut
from src.core.security import get_current_user
# PresentationFormatter removed — formatting is handled inline per endpoint


class FeedbackRequest(BaseModel):
    # Request body for recommendation feedback — farmer rates if recommendation was useful
    helpful: bool


router = APIRouter()


# Returns filtered recommendations for a farm — supports category, severity, type, and unread filters
@router.get("/{farm_id}", response_model=List[dict])
async def list_recommendations(
    farm_id: int,
    category: Optional[str] = Query(None, description="irrigation | temperature | humidity | soil | general"),
    severity: Optional[str] = Query(None, description="normal | warning | urgent"),
    type: Optional[str] = Query(None, description="urgent | improvement"),
    unread_only: bool = Query(False),
    limit: int = Query(50, le=200),
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """List recommendations for a farm, filterable by category, severity, and type."""
    await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    q = (
        select(Recommendation)
        .where(Recommendation.farm_id == farm_id)
        .order_by(desc(Recommendation.created_at))
        .limit(limit)
    )
    if category:
        q = q.where(Recommendation.category == category)
    if severity:
        q = q.where(Recommendation.severity == severity)
    if type == "urgent":
        q = q.where((Recommendation.is_alert == True) | (Recommendation.severity.in_(["urgent", "warning"])))
    elif type == "improvement":
        q = q.where((Recommendation.is_alert == False) & (Recommendation.severity == "normal"))
    if unread_only:
        q = q.where(Recommendation.is_read == False)

    result = await db.execute(q)
    recommendations = result.scalars().all()

    # Debug: log count of returned recommendations
    print(f"[DEBUG] Farm {farm_id}: Found {len(recommendations)} recommendations")
    if len(recommendations) == 0:
        # Check if any recommendations exist at all for this farm
        all_recs = await db.execute(select(Recommendation).where(Recommendation.farm_id == farm_id))
        print(f"[DEBUG] Total recommendations in DB for farm {farm_id}: {len(all_recs.scalars().all())}")

    # Serialize recommendations — safely extract enum values for frontend
    professional_recs = []
    for rec in recommendations:
        try:
            # Safely extract enum string values for category and severity
            category_value = rec.category.value if hasattr(rec.category, 'value') else str(rec.category)
            severity_value = rec.severity.value if hasattr(rec.severity, 'value') else str(rec.severity)

            professional_recs.append({
                "id": rec.id,
                "title": rec.message[:60] if rec.message else "توصية",
                "message": rec.message,
                "reasoning": rec.reasoning,
                "category": category_value,
                "severity": severity_value,
                "is_read": rec.is_read,
                "created_at": rec.created_at.isoformat() if rec.created_at else None,
            })
        except Exception as e:
            print(f"[ERROR] Recommendation {rec.id}: {e}")
            continue

    return professional_recs


@router.post("/{farm_id}/mark-read/{recommendation_id}", response_model=RecommendationOut)
async def mark_as_read(
    farm_id: int,
    recommendation_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """Mark a recommendation as read."""
    await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    result = await db.execute(
        select(Recommendation).where(
            Recommendation.id == recommendation_id,
            Recommendation.farm_id == farm_id,
        )
    )
    rec = result.scalar_one_or_none()
    if not rec:
        raise HTTPException(status_code=404, detail="Recommendation not found")

    rec.is_read = True
    await db.commit()
    await db.refresh(rec)
    return rec


@router.post("/{farm_id}/mark-all-read", response_model=dict)
async def mark_all_read(
    farm_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """Mark all recommendations for a farm as read."""
    await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    result = await db.execute(
        select(Recommendation).where(
            Recommendation.farm_id == farm_id,
            Recommendation.is_read == False,
        )
    )
    recs = result.scalars().all()
    for rec in recs:
        rec.is_read = True

    await db.commit()
    return {"marked_read": len(recs)}


@router.post("/{farm_id}/feedback/{recommendation_id}")
async def submit_recommendation_feedback(
    farm_id: int,
    recommendation_id: int,
    feedback: FeedbackRequest,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """
    Save farmer feedback on a recommendation (helpful or not).
    This feedback is used by the continual learning system to improve recommendation accuracy.
    Request body: {"helpful": true/false}
    """

    await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    result = await db.execute(
        select(Recommendation).where(
            Recommendation.id == recommendation_id,
            Recommendation.farm_id == farm_id,
        )
    )
    rec = result.scalar_one_or_none()
    if not rec:
        raise HTTPException(status_code=404, detail="Recommendation not found")

    # Save feedback and timestamp
    rec.helpful = feedback.helpful
    rec.feedback_at = datetime.now(timezone.utc)

    await db.commit()
    await db.refresh(rec)

    # Update FeedbackLearningBridge to recalculate recommendation accuracy
    try:
        from src.ml.feedback_integration import FeedbackLearningBridge
        bridge = FeedbackLearningBridge(db)
        accuracy = await bridge.calculate_feedback_accuracy(farm_id, days=7)
        print(f"[Feedback] Recommendation {recommendation_id}: {'helpful' if feedback.helpful else 'not helpful'}")
        print(f"[Stats] Farm {farm_id}: accuracy = {accuracy['overall_accuracy']:.1f}%")
    except Exception as e:
        print(f"[Warning] Feedback logging error: {e}")

    return {
        "id": rec.id,
        "helpful": rec.helpful,
        "feedback_at": rec.feedback_at.isoformat() if rec.feedback_at else None,
        "message": "Feedback recorded successfully"
    }


@router.get("/{farm_id}/feedback-stats")
async def get_feedback_stats(
    farm_id: int,
    days: int = 7,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """
    Returns feedback accuracy statistics for recommendations over the last N days.
    Useful for measuring model improvement over time.
    """
    await _get_farm_or_404(farm_id, int(current_user["sub"]), db)

    # Calculate the start of the stats window
    since = datetime.now(timezone.utc) - timedelta(days=days)

    # إجمالي التوصيات مع فيدباك
    result = await db.execute(
        select(
            func.count(Recommendation.id).label("total"),
            func.sum(func.cast(Recommendation.helpful, Integer)).label("helpful_count"),
            func.count(
                Recommendation.id
            ).filter(Recommendation.helpful == False).label("not_helpful_count")
        ).where(
            Recommendation.farm_id == farm_id,
            Recommendation.helpful.isnot(None),
            Recommendation.feedback_at >= since
        )
    )

    row = result.scalar_one()
    total = row.total or 0
    helpful = row.helpful_count or 0
    not_helpful = row.not_helpful_count or 0

    accuracy = (helpful / total * 100) if total > 0 else 0

    return {
        "days": days,
        "total_feedback": total,
        "helpful": helpful,
        "not_helpful": not_helpful,
        "accuracy_percentage": round(accuracy, 2),
        "pending_feedback": "Number of recommendations not yet rated by the farmer"
    }


async def _get_farm_or_404(farm_id: int, user_id: int, db: AsyncSession) -> Farm:
    """Fetch farm by ID and verify ownership. Raises 404 if not found or not owned by user."""
    result = await db.execute(
        select(Farm).where(Farm.id == farm_id, Farm.user_id == user_id)
    )
    farm = result.scalar_one_or_none()
    if not farm:
        raise HTTPException(status_code=404, detail="Farm not found")
    return farm
